/**
 * Builds src/data/carMedia.ts: a static map of `${makeId}/${modelId}` -> a
 * short gallery of real Wikimedia photos from the model's Wikipedia page.
 *
 * Run with: pnpm tsx scripts/fetch-car-media.ts
 */
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { makes } from '../src/data/catalog';
import { carImages } from '../src/data/carImages';

const UA = 'CarAtlasPro/1.0 (https://github.com/ErzenXz/supercars; demo project)';

interface MediaItem {
  title: string;
  type: string;
  showInGallery?: boolean;
  leadImage?: boolean;
  srcset?: { src: string; scale: string }[];
  caption?: { text?: string };
}

interface MediaListResponse {
  items?: MediaItem[];
}

const BAD_TERMS = [
  'logo',
  'badge',
  'emblem',
  'wordmark',
  'interior',
  'dashboard',
  'cockpit',
  'steering',
  'taillight',
  'headlight',
  'engine',
  'motor',
  'wheel',
  'diagram',
  'render',
  'sketch',
  'map',
  'brochure',
  'concept'
];

const buildTitle = (makeName: string, modelName: string): string => {
  const firstToken = makeName.split(/[\s-]/)[0].toLowerCase();
  return modelName.toLowerCase().startsWith(firstToken) ? modelName : `${makeName} ${modelName}`;
};

const sleep = (ms: number) => new Promise((resolveSleep) => setTimeout(resolveSleep, ms));

const normalizeUploadUrl = (src: string) => (src.startsWith('//') ? `https:${src}` : src);

const bestSrc = (item: MediaItem) => {
  const ordered = [...(item.srcset ?? [])].sort((a, b) => Number(a.scale[0] ?? 1) - Number(b.scale[0] ?? 1));
  const best = ordered[ordered.length - 1]?.src ?? ordered[0]?.src;
  return best ? normalizeUploadUrl(best) : null;
};

const tokenize = (value: string) =>
  value
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((token) => token.length >= 3);

const scoreItem = (item: MediaItem, tokens: string[]) => {
  const title = item.title.toLowerCase();
  const caption = item.caption?.text?.toLowerCase() ?? '';
  let score = 0;

  if (item.type !== 'image') return -100;
  if (/\.svg(?:\.png)?$/.test(title)) return -100;
  if (BAD_TERMS.some((term) => title.includes(term) || caption.includes(term))) score -= 16;
  if (/\.jpe?g$/.test(title)) score += 7;
  if (/\.webp$/.test(title)) score += 4;
  if (/\.png$/.test(title)) score += 1;
  if (item.showInGallery) score += 4;
  if (item.leadImage) score += 5;
  tokens.forEach((token) => {
    if (title.includes(token)) score += 2;
    if (caption.includes(token)) score += 1;
  });

  return score;
};

async function fetchGallery(title: string): Promise<MediaItem[]> {
  const url = `https://en.wikipedia.org/api/rest_v1/page/media-list/${encodeURIComponent(title)}`;
  const response = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!response.ok) return [];
  const json = (await response.json()) as MediaListResponse;
  return json.items ?? [];
}

async function main() {
  const output: Record<string, string[]> = {};

  for (const make of makes) {
    for (const model of make.models) {
      const key = `${make.id}/${model.id}`;
      const title = buildTitle(make.name, model.name);
      const tokens = unique(tokenize(`${make.name} ${model.name}`));

      try {
        const items = await fetchGallery(title);
        const chosen = items
          .map((item) => ({ item, score: scoreItem(item, tokens), src: bestSrc(item) }))
          .filter((candidate) => candidate.score > 0 && candidate.src)
          .sort((a, b) => b.score - a.score)
          .map((candidate) => candidate.src as string);

        const deduped = unique([
          ...(carImages[key] ? [carImages[key]] : []),
          ...chosen
        ]).slice(0, 6);

        if (deduped.length > 0) {
          output[key] = deduped;
          console.log(`✓ ${key}  ←  ${deduped.length} photos`);
        } else {
          console.log(`· ${key}  —  no gallery candidates`);
        }
      } catch (error) {
        if (carImages[key]) {
          output[key] = [carImages[key]];
        }
        console.log(`! ${key}  —  ${(error as Error).message}`);
      }

      await sleep(90);
    }
  }

  const body = Object.keys(output)
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(output[key])}`)
    .join(',\n');

  const file = `// AUTO-GENERATED by scripts/fetch-car-media.ts — do not edit by hand.
// Wikimedia Commons / Wikipedia-derived model galleries. Re-run the script to refresh.
export const carMedia: Record<string, string[]> = {
${body}
};
`;

  await writeFile(resolve('src', 'data', 'carMedia.ts'), file);
  console.log(`\nWrote ${Object.keys(output).length} model galleries.`);
}

function unique<T>(values: T[]) {
  return Array.from(new Set(values));
}

main();
