/**
 * Builds src/data/carImages.ts: a static map of `${makeId}/${modelId}` -> a
 * real photo URL from Wikimedia Commons (via the Wikipedia REST API).
 *
 * Run with: pnpm tsx scripts/fetch-car-images.ts
 */
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { makes } from '../src/data/catalog';

const UA = 'CarAtlasPro/1.0 (https://github.com/ErzenXz/supercars; demo project)';

interface PageImage {
  thumbnail?: { source: string };
}

const buildTitle = (makeName: string, modelName: string): string => {
  const firstToken = makeName.split(/[\s-]/)[0].toLowerCase();
  return modelName.toLowerCase().startsWith(firstToken) ? modelName : `${makeName} ${modelName}`;
};

async function fetchThumb(title: string): Promise<string | null> {
  const url =
    'https://en.wikipedia.org/w/api.php?action=query&prop=pageimages&format=json' +
    '&redirects=1&piprop=thumbnail&pithumbsize=800&titles=' +
    encodeURIComponent(title);
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) return null;
  const json = (await res.json()) as { query?: { pages?: Record<string, PageImage> } };
  const pages = json.query?.pages ?? {};
  const page = Object.values(pages)[0];
  return page?.thumbnail?.source ?? null;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const map: Record<string, string> = {};
  const misses: string[] = [];

  for (const make of makes) {
    for (const model of make.models) {
      const title = buildTitle(make.name, model.name);
      const key = `${make.id}/${model.id}`;
      try {
        const src = await fetchThumb(title);
        if (src) {
          map[key] = src;
          console.log(`✓ ${key}  ←  ${title}`);
        } else {
          misses.push(`${key} (${title})`);
          console.log(`· ${key}  —  no image for "${title}"`);
        }
      } catch (err) {
        misses.push(`${key} (${title})`);
        console.log(`! ${key}  —  error: ${(err as Error).message}`);
      }
      await sleep(120);
    }
  }

  const sortedKeys = Object.keys(map).sort();
  const body = sortedKeys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])}`).join(',\n');
  const file = `// AUTO-GENERATED by scripts/fetch-car-images.ts — do not edit by hand.
// Real model photos from Wikimedia Commons (CC-licensed). Re-run the script to refresh.
export const carImages: Record<string, string> = {
${body}
};
`;
  await writeFile(resolve('src', 'data', 'carImages.ts'), file);
  console.log(`\nWrote ${sortedKeys.length} image URLs. Misses: ${misses.length}`);
  if (misses.length) console.log('Missing (will fall back to silhouette):\n  ' + misses.join('\n  '));
}

main();
