// AUTO-GENERATED by scripts/fetch-car-media.ts — do not edit by hand.
// Wikimedia Commons / Wikipedia-derived model galleries. Re-run the script to refresh.
export const carMedia: Record<string, string[]> = {};
